# Generated by Django 6.0.4 on 2026-05-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность тарифа (дней)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена тарифа'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_purchase_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
    ]
