# Generated by Django 6.0.4 on 2026-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_tariff_duration_user_tariff_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания тарифа'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_type',
            field=models.CharField(blank=True, choices=[('day', 'Дневной (до 17:00)'), ('evening', 'Вечерний (после 17:00)'), ('unlimited', 'Безлимитный')], max_length=20, null=True, verbose_name='Тип тарифа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
