# Generated by Django 6.0.4 on 2026-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_tariff_end_date_user_tariff_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trainer',
            field=models.BooleanField(default=False, verbose_name='Тренер'),
        ),
    ]
