# Generated by Django 6.0.4 on 2026-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff_has_personal',
            field=models.BooleanField(default=False, verbose_name='Доступ к персональным тренировкам'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
    ]
