# Generated by Django 6.0.4 on 2026-05-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_tariff_has_personal_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
