# Generated by Django 6.0.4 on 2026-05-01 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('working_hours_weekdays', models.CharField(max_length=100, verbose_name='Будни')),
                ('working_hours_weekend', models.CharField(max_length=100, verbose_name='Выходные')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('has_towels', models.BooleanField(default=False, verbose_name='Полотенца')),
                ('has_restaurant', models.BooleanField(default=False, verbose_name='Ресторан/Кафе')),
                ('has_children_room', models.BooleanField(default=False, verbose_name='Детская комната')),
                ('has_sauna', models.BooleanField(default=False, verbose_name='Сауна')),
                ('has_solarium', models.BooleanField(default=False, verbose_name='Солярий')),
                ('has_hammam', models.BooleanField(default=False, verbose_name='Хамам')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_days', models.IntegerField(verbose_name='Длительность (дней)')),
                ('has_trainer', models.BooleanField(default=False, verbose_name='Персональная тренировка с тренером')),
                ('has_unlimited', models.BooleanField(default=False, verbose_name='Безлимитное посещение')),
                ('has_day_time', models.BooleanField(default=False, verbose_name='Посещение днем (до 17:00)')),
                ('has_evening_time', models.BooleanField(default=False, verbose_name='Посещение вечером (после 17:00)')),
                ('has_free_parking', models.BooleanField(default=False, verbose_name='Бесплатная парковка')),
                ('has_personal_locker', models.BooleanField(default=False, verbose_name='Собственный шкафчик')),
                ('has_fitness_testing', models.BooleanField(default=False, verbose_name='Анализ состава тела In Body')),
                ('has_guest_visit', models.BooleanField(default=False, verbose_name='3 гостевых визит')),
                ('has_solarium', models.BooleanField(default=False, verbose_name='Солярий 5 минут')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Ф.И.О.')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специализация')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Лет опыта')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='TrainerBio',
            fields=[
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bio', serialize=False, to='main.trainer')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Биография тренера',
                'verbose_name_plural': 'Биографии тренеров',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_minutes', models.IntegerField(verbose_name='Длительность (мин)')),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, verbose_name='Сложность')),
                ('goals', models.CharField(max_length=200, verbose_name='Цели')),
                ('max_participants', models.IntegerField(default=20, verbose_name='Макс. участников')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/', verbose_name='Изображение')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('booked_places', models.IntegerField(default=0, verbose_name='Записано человек')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.club', verbose_name='Клуб')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='active', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'unique_together': {('user', 'schedule')},
            },
        ),
    ]
