# Generated by Django 6.0.4 on 2026-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_active_user',
            field=models.BooleanField(default=False, verbose_name='Аккаунт активирован'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Телефон'),
        ),
    ]
