# Generated by Django 6.0.4 on 2026-05-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trainer_is_active_user_alter_trainer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='is_active_user',
        ),
    ]
