# Generated by Django 6.0.4 on 2026-05-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_trainer_is_active_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменена'),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='has_guest_visit',
            field=models.BooleanField(default=False, verbose_name='3 гостевых визита'),
        ),
    ]
