# Generated by Django 6.0.4 on 2026-05-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_trainer_email_remove_trainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Стаж работы'),
        ),
    ]
