# Generated by Django 6.0.4 on 2026-05-02 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_trainer_experience_years'),
        ('trainers', '0002_alter_personaltraining_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'is_trainer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='trainerbio',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bio', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerbio',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='trainerbio',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='trainerbio',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специализация'),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
