# Generated by Django 6.0.4 on 2026-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_workout_trainer_alter_trainerbio_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='has_guest_visit',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='has_solarium',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='has_trainer',
            field=models.BooleanField(default=False, verbose_name='Персональные тренировка с тренером'),
        ),
    ]
