# Generated by Django 6.0.4 on 2026-05-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_schedule_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='has_trainer',
        ),
        migrations.AddField(
            model_name='tariff',
            name='has_personal_trainings',
            field=models.BooleanField(default=False, verbose_name='Доступ к персональным тренировкам'),
        ),
    ]
