# Generated by Django 6.0.4 on 2026-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_tariff_has_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Фото клуба'),
        ),
    ]
