# Generated by Django 6.0.4 on 2026-05-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_club_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='club',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
