# Generated by Django 6.0.4 on 2026-05-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_schedule_club_delete_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
    ]
