# Generated by Django 6.0.4 on 2026-05-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_schedule_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('cancelled', 'Отменена')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='trainerbio',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='goals',
            field=models.CharField(max_length=100, verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(default='', upload_to='workouts/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
