# Generated by Django 6.0.4 on 2026-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_schedule_status_alter_trainerbio_specialty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название акции')),
                ('discount_percent', models.IntegerField(verbose_name='Скидка %')),
                ('valid_until', models.DateField(verbose_name='Действует до')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='main.promotion', verbose_name='Акции'),
        ),
    ]
